--- 商品 ---
CREATE TABLE "Product" (
    ProductID VARCHAR(100) PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    Price INT NOT NULL,
    Quantity INT NOT NULL
);


--- 訂單 ---
CREATE TABLE "Order" (
    OrderID VARCHAR(100) PRIMARY KEY,
    MemberID INT NOT NULL,
    Price INT NOT NULL,
    PayStatus INT NOT NULL DEFAULT 0,
    
    CONSTRAINT chk_order_paystatus
    CHECK (PayStatus IN (0, 1))
);


-- 訂單明細 ---
CREATE TABLE "OrderDetail" (
    OrderItemSN INT PRIMARY KEY,
    OrderID VARCHAR(30) NOT NULL,
    ProductID VARCHAR(20) NOT NULL,
    Quantity INT NOT NULL,
    StandPrice INT NOT NULL,
    ItemPrice INT NOT NULL,

        FOREIGN KEY (OrderID)
        REFERENCES "Order" (OrderID),

        FOREIGN KEY (ProductID)
        REFERENCES "Product" (ProductID)

);

--- 會員 ---
CREATE TABLE "Member" (
    MemberID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Phone VARCHAR(20) NOT NULL,
    Role VARCHAR(100) NOT NULL DEFAULT 'USER'
);


--- 購物車 ---
CREATE TABLE "Cart" (
    CartID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MemberID BIGINT NOT NULL,
    ProductID VARCHAR(100) NOT NULL,
    Quantity INT NOT NULL,

        FOREIGN KEY (MemberID)
        REFERENCES "Member" (MemberID),

        FOREIGN KEY (ProductID)
        REFERENCES "Product" (ProductID),

        UNIQUE (MemberID, ProductID)
);
ALTER TABLE "Cart"
ALTER COLUMN CartID
ADD GENERATED BY DEFAULT AS IDENTITY;
